### ISSUE TITLE
uninitialized constant RBS::Inline::Writer::StringIO (NameError)

### ISSUE THREAD

**Issue by stadia** [soutaro/rbs-inline#139]
I'm using the main branch.
When I ran 'bundle exec rbs-inline --output app', I got these errors.
ruby version is 3.3.6

`bundler: failed to load command: rbs-inline (/Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bin/rbs-inline)
/Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/lib/rbs/inline/writer.rb:19:in `initialize': uninitialized constant RBS::Inline::Writer::StringIO (NameError)

        @writer = RBS::Writer.new(out: StringIO.new(buffer))
                                       ^^^^^^^^
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/lib/rbs/inline/cli.rb:143:in `new'
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/lib/rbs/inline/cli.rb:143:in `block in run'
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/lib/rbs/inline/cli.rb:124:in `each'
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/lib/rbs/inline/cli.rb:124:in `run'
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bundler/gems/rbs-inline-b24479dd99ee/exe/rbs-inline:6:in `<top (required)>'
	from /Users/jeff.dean/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/bin/rbs-inline:25:in `load'`

**Comment by ParadoxV5** [comment]
* #136

**Comment by shunsugai** [comment]
This error seems to occur when psych is updated to version 5.2.0.
It is likely due to the following PR.

https://github.com/ruby/psych/pull/686
