### ISSUE TITLE
Suggestion: Enable automatically without writing `# rbs_inline: enabled`

### ISSUE THREAD

**Issue by sinsoku** [soutaro/rbs-inline#14]
It is tedious to insert the magic comment `# rbs_inline: enabled` into a file every time we start writing RBS type declarations.

It would be nice to be able to omit the magic comment, because if there is `# @rbs` or `#::` in the comment, it is obvious that the type definition is written for rbs-inline.

**Comment by soutaro** [comment]
> if there is # @rbs or #:: in the comment, it is obvious that the type definition is written for rbs-inline

It makes sense. 💡
