### ISSUE TITLE
Ignoring overloads after the first in method comments

### ISSUE THREAD

**Issue by euglena1215** [soutaro/rbs-inline#36]
## Description
When using `#::` comments to express method overloads, everything after the first `|` is ignored.

## Steps to Reproduce
Run `rbs-inline` on the following program:

```rb
#:: (String) -> String | (Integer) -> Integer
def foo(x)
  x
end
```

## Expected Result
The following should be generated:
```rbs 
#:: (String) -> String | (Integer) -> Integer 
def foo: (String) -> String | (Integer) -> Integer
```

## Actual Result
Everything after the first | is ignored, resulting in:
```rbs
#:: (String) -> String | (Integer) -> Integer 
def foo: (String) -> String
```

## Environment

- rbs-inline: 0.3.0

**Comment by soutaro** [comment]
The syntax accepts only one overload. So, having another overload after the `|` token doesn't work.

**Comment by ParadoxV5** [comment]
Is this the current way to write overloads?
```ruby
#:: (String) -> String
#:: (Integer) -> Integer
```
Perhaps OP’s expectation is more explicit?
```ruby
#:: (String) -> String
# | (Integer) -> Integer
```

**Comment by soutaro** [comment]
Hmm... 
Yeah, it's possible.

**Comment by euglena1215** [comment]
Oh, thank you very much. It seems to work as expected with the following.

```
#:: (String) -> String
#:: (Integer) -> Integer
```

I also found the following on the Wiki:

> Having multiple #:: syntax generates method definition with overloads.

My issue was not so much a syntax problem, but rather that I felt rbs-inline could not express overloads. I will close this issue now that I know I was mistaken.

Thank you for your comments!
