### ISSUE TITLE
Singleton methods are output as instance methods

### ISSUE THREAD

**Issue by sinsoku** [soutaro/rbs-inline#37]
### Steps to reproduce

```console
$ cat issue.rb
# rbs_inline: enabled

class A
  class << self
    def m
    end
  end
end

$ rbs-inline issue.rb
# Generated from issue.rb with RBS::Inline

class A
  def m: () -> untyped
end

🎉 Generated 1 RBS files under
```

### Expected behavior

It should output the singleton methods.

### Actual behavior

The definition of the instance method is output.

**Comment by ParadoxV5** [comment]
As listed on [the roadmap](https://github.com/soutaro/rbs-inline/wiki/Roadmap), support for singleton methods are on their way.
