### ISSUE TITLE
`@rbs class` syntax

### ISSUE THREAD

**Issue by soutaro** [soutaro/rbs-inline#66]
Some methods allow defining methods to another class inside blocks.

```rb
module Foo
  class_methods do
    # Defines `ClassMethods` module ande defines methods in it
    def foo = 123
  end
end
```

I plan to introduce `@rbs class C` and `@rbs module M` commands, that wraps the contents of the block inside a `class`/`module` declaration.

```rb
module Foo
  class_methods do
    # @rbs module ClassMethods
    def foo = 123
  end
end
```

(`end` is missing, but we know it's acceptable from Haml.)

**Comment by ParadoxV5** [comment]
Example with just Ruby stdlib:
```ruby
module Foo
  instance_eval do
    # @rbs module ClassMethods
    def foo = 123
  end
end
```

**Comment by soutaro** [comment]
Implemented in #69, with a minor syntax change.

```
module Foo
  # The @rbs module annotation is given above the block call.

  # @rbs module ClassMethods
  class_methods do
    def foo = 123
  end
end
```

**Comment by soutaro** [comment]
@ParadoxV5 By the way, the `@rbs module` syntax would not be sufficient for the `instance_eval` example.

What we need is to do it in singleton class context. Not defining another module for the block.

```rbs
module Foo
  # We don't want ClassMethods module...
  module ClassMethods
    def foo: () -> untyped
  end

  def self.foo: () -> untyped    # This is expected
end
```

Maybe we need `@rbs class <<self`???

**Comment by ParadoxV5** [comment]
We *could* just _not_ support it.
Is there a concrete reason one’d use `instance_eval do` over `class << self` in Ruby?
